# Generated by Django 6.1 on 2026-08-21 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investigation_id', models.CharField(max_length=30, unique=True)),
                ('test_name', models.CharField(max_length=150)),
                ('test_type', models.CharField(max_length=100)),
                ('diagnostic_center', models.CharField(max_length=200)),
                ('scheduled_date', models.DateField()),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('SCHEDULED', 'Scheduled'), ('SAMPLE_COLLECTED', 'Sample Collected'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('REPORT_AVAILABLE', 'Report Available'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=30)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to='patients.patient')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_investigations', to='doctors.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('review_status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('UNDER_REVIEW', 'Under Review'), ('REVIEWED', 'Reviewed')], default='PENDING_REVIEW', max_length=30)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='patients.patient')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_reports', to=settings.AUTH_USER_MODEL)),
                ('investigation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='diagnostics.investigation')),
            ],
        ),
    ]
