# Generated by Django 6.1 on 2026-08-21 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.CharField(max_length=30, unique=True)),
                ('specialization', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=200)),
                ('experience_years', models.PositiveIntegerField()),
                ('hospital', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=100)),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('bio', models.TextField()),
                ('languages', models.CharField(help_text='Comma-separated languages spoken', max_length=200)),
                ('location', models.CharField(max_length=150)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
