# Generated by Django 6.1 on 2026-08-25 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('MORNING', 'Morning (6:00 AM - 11:00 AM)'), ('AFTERNOON', 'Afternoon (12:00 PM - 3:00 PM)'), ('EVENING', 'Evening (7:00 PM - 11:00 PM)')], max_length=15)),
                ('scheduled_time', models.TimeField(help_text='Local reminder time in the selected period')),
                ('phone_number', models.CharField(help_text='E.164 number, e.g. +919876543210', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sent_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_reminders', to='patients.patient')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='pharmacy.prescription')),
            ],
            options={
                'ordering': ['scheduled_time'],
                'constraints': [models.UniqueConstraint(fields=('prescription', 'period'), name='one_reminder_per_prescription_period')],
            },
        ),
    ]
