# Generated by Django 6.1 on 2026-08-25 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('pharmacy', '0002_medicationreminder'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='medicationreminder',
            name='one_reminder_per_prescription_period',
        ),
        migrations.AddField(
            model_name='medicationreminder',
            name='message',
            field=models.CharField(default='Take your medicine', max_length=160),
        ),
        migrations.AlterField(
            model_name='medicationreminder',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='pharmacy.prescription'),
        ),
        migrations.AddConstraint(
            model_name='medicationreminder',
            constraint=models.UniqueConstraint(fields=('patient', 'period'), name='one_reminder_per_patient_period'),
        ),
    ]
