import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { ArrowRight, HeartPulse, LockKeyhole, Mail } from "lucide-react";
import { getCurrentUser, saveCurrentUser } from "../utils/sessionUser";

const initial = { name: "", email: "", password: "", gender: "", age: "", height: "", weight: "", bloodGroup: "" };
const input = "mt-1.5 w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-teal-600 focus:ring-4 focus:ring-teal-100";

export default function PatientLogin() {
  const navigate = useNavigate();
  const [mode, setMode] = useState("signin");
  const [data, setData] = useState(initial);
  const [otp, setOtp] = useState("");
  const [message, setMessage] = useState("");
  useEffect(() => { if (localStorage.getItem("healora.token") && getCurrentUser()) navigate("/patients", { replace: true }); }, [navigate]);
  const change = (key) => (e) => setData({ ...data, [key]: e.target.value });
  const finishLogin = (e) => { e.preventDefault(); localStorage.setItem("healora.token", "mock-access-token-12345"); saveCurrentUser(data); navigate("/patients"); };
  const create = (e) => { e.preventDefault(); setMode("signin"); };
  const verifyOtp = (e) => { e.preventDefault(); if (otp === "123456") { setMode("signin"); setMessage("Password reset complete. Please sign in."); } else setMessage("Enter the demo OTP: 123456"); };
  const ProfileFields = () => <div className="grid grid-cols-2 gap-3"><label>Gender<select required value={data.gender} onChange={change("gender")} className={input}><option value="">Select</option><option>Female</option><option>Male</option><option>Other</option></select></label><label>Age<input required type="number" min="1" max="120" value={data.age} onChange={change("age")} className={input} /></label><label>Height<input required value={data.height} onChange={change("height")} placeholder="168 cm" className={input} /></label><label>Weight<input required value={data.weight} onChange={change("weight")} placeholder="62 kg" className={input} /></label><label className="col-span-2">Blood group<select required value={data.bloodGroup} onChange={change("bloodGroup")} className={input}><option value="">Select blood group</option>{["A+","A-","B+","B-","AB+","AB-","O+","O-"].map((value) => <option key={value}>{value}</option>)}</select></label></div>;
  return <main className="min-h-[calc(100vh-5rem)] bg-gradient-to-br from-[#123744] via-[#17616a] to-[#0b4f5d] px-5 py-14"><section className="mx-auto w-full max-w-lg rounded-[2rem] bg-white p-7 shadow-2xl sm:p-10"><div className="flex items-center gap-2 text-[#075778]"><HeartPulse className="h-7 w-7" /><span className="text-xl font-bold">Healora</span></div><p className="mt-7 text-xs font-bold uppercase tracking-[.16em] text-teal-700">Patient portal</p><h1 className="mt-2 text-3xl font-semibold text-slate-900">{mode === "create" ? "Create account" : mode === "forgot" ? "Reset password" : "Welcome back"}</h1>{message && <p className="mt-4 rounded-xl bg-amber-50 p-3 text-xs font-semibold text-amber-800">{message}</p>}
    {mode === "signin" && <form onSubmit={finishLogin} className="mt-6 space-y-4"><label className="block text-sm font-semibold text-slate-700">Full name<input required value={data.name} onChange={change("name")} placeholder="Enter your name" className={input} /></label><label className="block text-sm font-semibold text-slate-700">Email address<div className="relative"><Mail className="absolute left-3 top-4 h-4 w-4 text-slate-400" /><input required type="email" value={data.email} onChange={change("email")} placeholder="name@gmail.com" className={`${input} pl-10`} /></div></label><label className="block text-sm font-semibold text-slate-700">Password<div className="relative"><LockKeyhole className="absolute left-3 top-4 h-4 w-4 text-slate-400" /><input required type="password" value={data.password} onChange={change("password")} className={`${input} pl-10`} /></div></label><fieldset className="rounded-xl bg-slate-50 p-4 text-sm font-semibold text-slate-700"><legend className="px-1 text-xs font-bold uppercase tracking-wider text-slate-500">Health profile for reports</legend><ProfileFields /></fieldset><button type="button" onClick={() => { setMessage(""); setMode("forgot"); }} className="text-xs font-bold text-teal-700">Forgotten password?</button><button className="w-full rounded-xl bg-[#075778] py-3.5 font-bold text-white">Sign in <ArrowRight className="ml-1 inline h-4 w-4" /></button><p className="text-center text-sm text-slate-500">New to Healora? <button type="button" onClick={() => { setMessage(""); setMode("create"); }} className="font-bold text-teal-700">Create an account</button></p></form>}
    {mode === "create" && <form onSubmit={create} className="mt-6 space-y-4 text-sm font-semibold text-slate-700"><label className="block">Full name<input required value={data.name} onChange={change("name")} className={input} /></label><label className="block">Email address<input required type="email" value={data.email} onChange={change("email")} className={input} /></label><ProfileFields /><label className="block">Password<input required type="password" minLength="6" value={data.password} onChange={change("password")} className={input} /></label><button className="w-full rounded-xl bg-[#075778] py-3.5 font-bold text-white">Create account</button></form>}
    {mode === "forgot" && <form onSubmit={verifyOtp} className="mt-6 space-y-4"><p className="rounded-xl bg-cyan-50 p-4 text-center text-sm text-cyan-900">Demo OTP: <strong className="ml-2 text-xl tracking-[.25em]">123456</strong></p><label className="block text-sm font-semibold text-slate-700">OTP<input required maxLength="6" value={otp} onChange={(e) => setOtp(e.target.value)} className={`${input} text-center tracking-[.3em]`} /></label><button className="w-full rounded-xl bg-[#075778] py-3.5 font-bold text-white">Verify OTP</button></form>}
  </section></main>;
}
