# Generated by Django 6.1 on 2026-08-21 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_id', models.CharField(max_length=30, unique=True)),
                ('specialization', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('APPOINTMENT_SCHEDULED', 'Appointment Scheduled'), ('COMPLETED', 'Completed'), ('FOLLOW_UP_REQUIRED', 'Follow-up Required'), ('CLOSED', 'Closed')], default='REQUESTED', max_length=30)),
                ('requested_date', models.DateField(auto_now_add=True)),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='patients.patient')),
                ('referring_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_referrals', to='doctors.doctor')),
                ('specialist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_referrals', to='doctors.doctor')),
            ],
        ),
    ]
